THO = {
"Ao thu l¹nh lÏo n­íc trong veo", 
"Mét chiÕc thuyÒn c©u bĞ tÎo teo",
"Sãng biÕc theo lµn h¬i gîn tİ",
"L¸ vµng tr­íc giã sÏ ®­a vÌo",
"TÇng m©y l¬ löng trêi xanh ng¾t",
"Ngâ tróc quanh co kh¸ch v¾ng teo",
"Tùa gèi, «m cÇn l©u ch¼ng ®­îc",
"C¸ ®©u ®íp ®éng d­íi ch©n bÌo",

-----------------------------------------------------
"B­íc tíi §Ìo Ngang, bãng xÕ tµ",
"Cá c©y chen ®¸, l¸ chen hoa",
"Lom khom d­íi nói, tiÒu vµi chó",
"L¸c ®¸c bªn s«ng, rî mÊy nhµ",
"Nhí n­íc ®au lßng, con quèc quèc",
"Th­¬ng nhµ mái miÖng, c¸i gia gia",
"Dõng ch©n ®øng l¹i trêi, non, n­íc",
"Mét m¶nh t×nh riªng, ta víi ta",
-- "Qua §Ìo Ngang - Bµ HuyÖn Thanh Quan"
------------------------------------------------------------
"Hoa cá ngïi ngïi ngãng giã ®«ng",
"Chóa Xu©n ®©u hìi cã hay kh«ng",
"M©y gi¨ng ¶i B¾c tr«ng tin nh¹n",
"Ngµy xÕ non Nam bÆt tiÕng hång",
"Bê câi x­a ®µ chia ®Êt kh¸c",
"N¾ng s­¬ng nay hµ ®éi trêi chung",
"Chõng nµo Th¸nh ®Ó ©n soi thÊu",
"Mét trËn m­a nhuÇn röa nói s«ng",
--Ngong Gio Dong- Nguyen Dinh Chieu
"§· bÊy l©u nay b¸c tíi nhµ",
"TrÎ thêi ®i v¾ng, chî thêi xa",
"Ao s©u n­íc c¶, kh«n chµi c¸",
"V­ên réng rµo th­a, khã ®uæi gµ",
"C¶i chöa ra c©y, cµ míi nô",
"BÇu võa rông rèn, m­íp ®­¬ng hoa",
"§Çu trß tiÕp kh¸ch, trÇu kh«ng cã",
"B¸c ®Õn ch¬i ®©y ta víi ta",
-- Ban den choi nha - Nguyen Khuyen
"§ªm thu buån l¾m! ChŞ H»ng ¬i! ",
"TrÇn thÕ em nay ch¸n nöa råi. ",
"Cung quÕ ®· ai ngåi ®ã chöa? ",
"Cµnh ®a xin chŞ nh¾c lªn ch¬i. ",
"Cã bÇu, cã b¹n, can chi tñi, ",
"Cïng giã, cïng m©y, thÕ míi vui. ",
"Råi cø mçi n¨m r»m th¸ng t¸m. ",
"Tùa nhau tr«ng xuèng thÕ gian, c­êi.",
-- Muon lam thang cuoi- Tan Da
"N¨m gian nhµ cá thÊp le te,",
"Ngâ tèi ®ªm s©u ®ãm lËp loÌ.",
"L­ng giËu phÊt ph¬ mµu khãi nh¹t,",
"Lµn ao lãng l¸nh bãng tr¨ng loe.",
"Da trêi ai nhuém mµ xanh ng¾t?",
"M¾t l·o kh«ng vÇy còng ®á hoe.",
"R­îu tiÕng r»ng hay, hay ch¶ mÊy.",
"§é n¨m ba chĞn ®· say nhÌ.",
-- Thu am - Nguyen Khuyen
"Trêi thu xanh ng¾t mÊy tÇng cao,",
"CÇn tróc l¬ ph¬ giã h¾t hiu.",
"N­íc biÕc tr«ng nh­ tÇng khãi phñ,",
"Song th­a ®Ó mÆc bãng tr¨ng vµo.",
"MÊy chïm tr­íc giËu hoa n¨m ngo¸i,",
"Mét tiÕng trªn kh«ng ngçng n­íc nµo?",
"Nh©n høng còng võa toan cÊt bót,",
"NghÜ ra l¹i thÑn víi «ng §µo.",
--Thu Vinh- Nguyen Khuyen
"Bùc g× b»ng g¸i trùc phßng kh«ng?",
"T¬ t­ëng v× chung mét tÊm chång.",
"Trªn g¸c rång m©y ngao ng¸n ®îi,",
"Bªn trêi c¸ n­íc ngÈn ng¬ tr«ng.",
"Mua vui, l¾m lóc c­êi c­êi g­îng,",
"Gi¶ d¹i, nhiÒu khi nãi nãi b«ng.",
"Míi biÕt cã chång nh­ cã c¸nh,",
"Giang s¬n g¸nh v¸c nhÑ b»ng l«ng.",
--Muon Lay Chong- Nguyen Khuyen
"NghÜ chuyÖn ®êi x­a còng nùc c­êi,",
"Sù ®êi ®Õn thÕ, thÕ thêi th«i!",
"Rõng xanh nói ®á h¬n ngµn dÆm,",
"N­íc ®éc ma thiªng mÊy v¹n ng­êi.",
"KhoĞt rçng ruét gan trêi ®Êt c¶,",
"Ph¸ tung phªn giËu h¹ di råi.",
"Th«i th«i ®Õn thÕ thêi th«i nhØ,",
"MÊy tr¾ng vÒ ®©u n­íc ch¶y xu«i.",
--Hoai Co
"Tan chî võa nghe tiÕng sóng T©y",
"Mét bµn cê thÕ phót sa tay",
"Bá nhµ lò trÎ l¬ x¬ ch¹y",
"MÊt æ bÇy chim d¸o d¸c bay",
"BÕn NghĞ cña tiÒn tan bät n­íc",
"§ång Nai tranh ngãi nhuém mÇu m©y",
"Hái trang dÑp lo¹n nµy ®©u v¾ng?",
"Nì ®Ó d©n ®en m¾c n¹n nµy! ",
--Chay Giac- Nguyen Dinh Chieu
"V× c©u danh nghÜa ph¶i ®i ra,",
"Day mòi thuyÒn nan d¹ xãt xa,",
"Ng­êi dÔ muèn chi n­¬ng ®Êt kh¸ch,",
"Trêi ®µ khiÕn vËy mÕn vua ta .",
"Mét ph­¬ng thµ tr¸nh ®­êng gai gèc,",
"Tr¨m tuæi cho trßn phËn tãc d¹",
"ChĞn r­îu Êm lßng xin c¹n chĞn,",
"Nhí nhau ngµy kh¸c biÕt sao mµ.",
--Tu biet co nhan
"Quanh n¨m bu«n b¸n ë mom s«ng,",
"Nu«i ®ñ n¨m con víi mét chång.",
"LÆn léi th©n cß khi qu·ng v¾ng,",
"Eo sÌo mÆt n­íc buæi ®ß ®«ng.",
"Mét duyªn hai nî ©u ®µnh phËn",
"N¨m n¾ng m­êi m­a d¸m qu¶n c«ng.",
"Cha mÑ thãi ®êi ¨n ë b¹c,",
"Cã chång hê h÷ng còng nh­ kh«ng.",
-- Thuong Vo- Tu Xuong
"ë phè Hµng N©u cã phçng sµnh",
"M¾t thêi thao l¸o, mÆt thêi xanh",
"Vuèt r©u nŞnh vî, con bu nã",
"Qu¾c m¾t khinh ®êi, c¸i bé anh",
"Bµi b¹c kiÖu cê cao nhÊt xø",
"R­îu chÌ trai g¸i ®ñ tam khoanh",
"ThÕ mµ cø nghÜ r»ng ta giái,",
"Cø viÖc ¨n ch¬i ch¼ng häc hµnh",
-- Phong Sanh- Tu Xuong
"Nhµ n­íc ba n¨m më mét khoa,",
"Tr­êng Nam thi lÉn víi tr­êng Hµ.",
"L«i th«i sÜ tö vai ®eo lä,",
"Ëm oÑ quan tr­êng miÖng thĞt loa.",
"Läng c¾m rîp trêi, quan Sø ®Õn,",
"V¸y lª quĞt ®Êt, mô ®Çm ra. ",
"Nh©n tµi ®Êt B¾c nµo ai ®ã ?",
"Ngo¶nh cæ mµ tr«ng c¶nh n­íc nhµ !",
--Vinh Khoa Thi Huong- Tu Xuong
"Hµ Nam danh gi¸ nhÊt «ng cß ",
"Tr«ng thÊy ai ai ch¼ng d¸m ho.",
"Hai m¸i trèng toang ®µnh chŞu giét ",
"T¸m giê chu«ng ®¸nh ph¶i n»m co ",
"Ng­êi quªn mÊt thÎ ©u trêi c·i ",
"Chã ch¹y ra ®­êng cã chñ lo ",
"Ngí ngÈn ®i xia may ví ®­îc ",
"ChuyÕn nµy ¾t h¼n kiÕm ¨n to",
-- Ong Co -- Tu Xuong
"Th¸i hoµ vò trô bÊt Ngu Chu, ",
"Hç chiÕn giao tranh tiÕu l­ìng thï. ",
"Xuyªn huyÕt s¬n hµi tuú xø h÷u, ",
"Uyªn ng­ tïng t­íc vŞ thuú khu. ",
"Trïng h­ng dÜ bèc ®å giang m·, ",
"HËu ho¹n ­ng phßng nhËp thÊt khu, ",
"ThÕ sù ®¸o ®Çu h­u thuyÕt tr­íc, ",
"Tuı ng©m tr¹ch b¹n nhËm nhµn du.",
-- Cam hung- Nguyen Binh Khiem
"Bİch tÈm tiªn s¬n triÖt ®Ó thanh, ",
"Cù ngao ®íi ®¾c ngäc hå sinh. ",
"§¸o ®Çu th¹ch h÷u bæ thiªn lùc, ",
"Tr­íc c­íc trµo v« quyÓn ®Şa thanh. ",
"V¹n lı §«ng minh quy b¶ ¸c, ",
"øc niªn Nam cùc ®iÖn long b×nh. ",
"Ng· kim dôc triÓn phï nguy lùc, ",
"V·n kh­íc quan hµ cùu ®Õ thµnh.",
--Cu Ngao Doi Son- Nguyen Binh Khiem
"ThËp nhŞ thiÒu quang xu©n nhÊt ®oµn, ",
"NhÊt thiªn liÖu tiÔu tèng d­ hµn. ",
"Khinh ©m t¸ vò x©m hoa dŞ, ",
"Tµn tuyÕt nh©n phong truş liÔu nan. ",
"Tó th¸t giai nh©n ®ª ngäc tr­íng, ",
"H­¬ng nhai tuı kh¸ch xóc kim an. ",
"Toµn kiÒn tù h÷u thÇn c«ng t¹i, ",
"DÜ b¸ d­¬ng hoµ m·n tÕ bµn.",
--Xuan Han- Nguyen Binh Khiem
"Tr¶i mÊy thu nay vÉn h·y cßn, ",
"Cí sao khi khuyÕt l¹i khi trßn? ",
"Hái con B¹ch Thè ®µ bao tuæi? ",
"Hái chŞ H»ng Nga ®· mÊy con? ",
"§ªm tèi cí sao soi g¸c tİa? ",
"Ngµy xanh cßn thÑn mÊy vÇng trßn. ",
"N¨m canh l¬ löng chê ai ®ã? ",
"Hay cã t×nh riªng mÊy n­íc non?",
--Van Nguyet- Ho Xuan Huong
"ChiÒu trêi b¶ng l¶ng bãng hoµng h«n, ",
"TiÕng èc xa ®­a lÈn trèng ®ån. ",
"G¸c m¸i, ng­ «ng vÒ viÔn phè, ",
"Gâ sõng, môc tö l¹i c« th«n. ",
"Ngµn mai giã cuèn chim bay mái, ",
"DÆm liÔu s­¬ng sa kh¸ch b­íc dån. ",
"KÎ chèn trang ®µi, ng­êi l÷ thø, ",
"LÊy ai mµ kÓ nçi hµn «n?",
-- Buoi Chieu Lu Thu-- Ba Huyen Thanh Quan
"Th¸nh thãt tµu tiªu mÊy h¹t m­a, ",
"Khen ai khĞo vÏ c¶nh tiªu s¬. ",
"Xanh om cæ thô trßn xoe t¸n, ",
"Tr¾ng xo¸ tr­êng giang ph¼ng lÆng tê. ",
"BÇu dèc giang s¬n, say chÊp r­îu, ",
"Tói l­ng phong nguyÖt, nÆng v× th¬. ",
"Cho hay c¶nh còng ­a ng­êi nhØ, ",
"ThÊy c¶nh ai mµ ch¼ng ngÈn ng¬.",
--Tuc Canh Chieu Thu- Ba Huyen Thanh Quan
"§Ö nhÊt nam thiªn Êy c¶nh nµy ",
"ThuyÒn nan ®ãn kh¸ch m¸y chÌo lay ",
"Hai bªn qu¶ nói lång h­¬ng suèi ",
"Bèn mÆt hoa ngµn rñ bãng c©y ",
"Cöa PhËt l¬ th¬ tÇng ®¸ d·y ",
"Chïa tiªn b¸t ng¸t khãi h­¬ng bay ",
"Nam v« tiÕng dËy th­a trÇn tôc ",
"Non n­íc Bång Lai míi thÊy ®©y!",
--C¶nh H­¬ng S¬n-- Ba Huyen Thanh Quan
"Vµng to¶ non t©y, bãng ¸c tµ, ",
"§Çm ®Çm ngän cá, tuyÕt phun hoa. ",
"Ngµn mai l¸c ®¸c, chim vÒ tæ, ",
"DÆm liÔu b©ng khu©ng, kh¸ch nhí nhµ. ",
"Cßi môc thĞt tr¨ng miÒn kho¸ng d·, ",
"Chµi ng­ tung giã b·i b×nh sa. ",
"Lßng quª mét b­íc nh­êng ngao ng¸n, ",
"MÊy kÎ t×nh chung cã thÊu lµ?",
--Chieu hom nho nha- Ba Huyen Thanh Quan
"Thµnh th­îng ®èng v©n thiªn lı ©m, ",
"L­¬ng viªn hoa liÔu m¹c trÇm trÇm. ",
"Cao ®­êng l­ìng xø t­ nhi lÖ, ",
"B¹c ho¹n tam xu©n c¶m cùu t©m. ",
"§èi th¸p bÇn thª phanh b¾c mİnh, ",
"Xao m«n tiÓu n÷ léng nam ©m. ",
"Bang gia h÷u ®¹o tri hµ dông? ",
"NhÊt bÖnh tha ®µ tuÕ tù th©m.",
-- Bac mo tu gia- Cao Ba Quat
"Bİch tiÔu hiªn kh«ng phong ®¶o xuy, ",
"Yªn thanh s­¬ng kİnh lËu nh­ ty. ",
"§an l­¬ng tr­íc m¹n v« tµng diÖu, ",
"B¹ch ®iÓu phiªn duy bÊt thô ky. ",
"B·o tÊt ng©m tµn nh©n tù viÔn, ",
"û l©u t©m t¹i ng· ­ng tri. ",
"T¶o mai v·n cóc tung s¬ phãng, ",
"D· kh¸n dao dao h÷u kû chi.",
-- Bac Mo-- Cao Ba Quat
}
TEN_BAI = {
"Thu §iÕu - NguyÔn KhuyÕn",
"Qua §Ìo Ngang - Bµ HuyÖn Thanh Quan",
"Ngãng Giã §«ng - NguyÔn §×nh ChiÓu",
"B¹n ®Õn ch¬i nhµ - NguyÔn KhuyÕn",
"Muèn lµm th»ng cuéi - T¶n §µ",
"Thu Èm - NguyÔn KhuyÕn",
"Thu vŞnh - NguyÔn KhuyÕn",
"Muèn lÊy chång - NguyÔn KhuyÕn",
"Hoµi Cè - NguyÔn KhuyÕn",
"Ch¹y giÆc - NguyÔn §×nh ChiÓu",
"Tõ biÖt cè nh©n - NguyÔn §×nh ChiÓu",
"Th­¬ng vî - Tó X­¬ng",
"Phçng sµnh - Tó X­¬ng",
"VŞnh khoa thi H­¬ng - Tó X­¬ng",
"¤ng Cß - Tó X­¬ng",
"C¶m høng - NguyÔn BØnh Khiªm",
"Cù ngao ®íi s¬n - NguyÔn BØnh Khiªm",
"Xu©n hµn - NguyÔn BØnh Khiªm",
"VÊn NguyÖt - Hå Xu©n H­¬ng",
"Buæi chiÒu l÷ thø - Bµ HuyÖn Thanh Quan",
"Tøc c¶nh chiÒu thu - Bµ HuyÖn Thanh Quan",
"C¶nh H­¬ng S¬n - Bµ HuyÖn Thanh Quan",
"ChiÒu h«m nhí nhµ - Bµ HuyÖn Thanh Quan",
"B¹c mé t­ gia - Cao B¸ Qu¸t",
"B¹c mé - Cao B¸ Qu¸t",
}
